
foreground = #E8F1FA
background = #00182D
cursor-color = #E8F1FA
cursor-text = #00182D

selection-foreground = #E8F1FA
selection-background = #407FB7

# Note: Preserved from Kitty color0-color15 exactly. Don't know if they work correctly
palette = 0=#646567
palette = 1=#E69679
palette = 2=#B8D698
palette = 3=#FDD48F
palette = 4=#8EBAE5
palette = 5=#F19EB1
palette = 6=#89CCCF
palette = 7=#E8F1FA

palette = 8=#000C17
palette = 9=#CC071E
palette = 10=#57AB27
palette = 11=#F6A800
palette = 12=#00549F
palette = 13=#E30066
palette = 14=#0098A1
palette = 15=#CFD1D2

