foreground              #E8F1FA
background              #00182D
cursor                  #E8F1FA
cursor_text_color        #00182D
selection_foreground     #E8F1FA
selection_background     #407FB7
url_color                #8EBAE5
active_border_color      #8EBAE5
inactive_border_color    #646567
bell_border_color        #FDD48F
visual_bell_color        #FDD48F

# Tab bar
tab_bar_background       #000C17
active_tab_foreground    #00182D
active_tab_background    #8EBAE5
active_tab_font_style    bold
inactive_tab_foreground  #9C9E9F
inactive_tab_background  #00182D
inactive_tab_font_style  normal
tab_bar_margin_color     #000C17

mark1_foreground         #00182D
mark1_background         #8EBAE5
mark2_foreground         #00182D
mark2_background         #E96088
mark3_foreground         #00182D
mark3_background         #FDD48F

# MUTED

color0                   #646567
color1                   #E69679
color2                  #B8D698
color3                  #FDD48F
color4                  #8EBAE5
color5                  #F19EB1
color6                  #89CCCF
color7                  #E8F1FA

# BRIGHT

color8                   #000C17
color9                   #CC071E
color10                   #57AB27
color11                   #F6A800
color12                   #00549F
color13                   #E30066
color14                   #0098A1
color15                   #CFD1D2



